import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabase'
import { getProfile } from '../lib/profiles'
import { format, parseISO, differenceInDays, getDate } from 'date-fns'
import { fr } from 'date-fns/locale'

export default function Comptes({ userId }) {
  const [depenses, setDepenses] = useState([])
  const [echeances, setEcheances] = useState([])
  const [tab, setTab] = useState('depenses')
  const [labelInput, setLabelInput] = useState('')
  const [montantInput, setMontantInput] = useState('')
  const [newEch, setNewEch] = useState({ label: '', montant: '', jour: '' })
  const [loading, setLoading] = useState(true)
  useEffect(() => { fetchAll(); const ch1=supabase.channel('dep').on('postgres_changes',{event:'*',schema:'public',table:'depenses'},fetchAll).subscribe();const ch2=supabase.channel('ech').on('postgres_changes',{event:'*',schema:'public',table:'echeances'},fetchAll).subscribe();return()=>{supabase.removeChannel(ch1);supabase.removeChannel(ch2)}},[])
  async function fetchAll(){const[{ data:d},{data:e}]=await Promise.all([supabase.from('depenses').select('*').order('created_at',{ascending:false}),supabase.from('echeances').select('*').order('jour_du_mois')]);if(d)setDepenses(d);if(e)setEcheances(e);setLoading(false)}
  async function addDepense(){if(!labelInput.trim()||!montantInput)return;await supabase.from('depenses').insert({label:labelInput.trim(),montant:parseFloat(montantInput),par:userId,date:format(new Date(),'yyyy-MM-dd'),pinned:false});setLabelInput('');setMontantInput('')}
  async function togglePin(dep){await supabase.from('depenses').update({pinned:!dep.pinned}).eq('id',dep.id)}
  async function deleteDepense(id){await supabase.from('depenses').delete().eq('id',id)}
  async function addEcheance(){if(!newEch.label||!newEch.montant|| !newEch.jour)return;await supabase.from('echeances').insert({label:newEch.label,montant:parseFloat(newEch.montant),jour_du_mois:parseInt(newEch.jour),vraif:true});setNewEch({label:'',montant:'',jour:''})}
  async function toggleEcheance(ech){await supabase.from('echeances').update({actif:!ech.actif}).eq('id',ech.id)}
  async function deleteEcheance(id){await supabase.from('echeances').delete().eq('id',id)}
  const today=new Date(), todayDay=getDate(today)
  const alerts=echeances.filter(e=>{if(!e.actif)return false;let diff=e.jour_du_mois-todayDay;if(diff<0){ const d=new Date(today.getFullYear(),today.getMonth()+1,0).getDate();diff=d-todayDay+e.jour_du_mois}return diff>=0&&diff<=5})
  const sorted=[...depenses].sort((a,b)=>({a.pinned?-1:0}-{b.pinned?-1:0}))
  const total=depenses.reduce((s,d)=>s+parseFloat(d.montant),0)
  if(loading)return <div className="p-6 text-center text-gray-400">Chargement…</div>
  return(<div className="p-4 page-enter">
    {alerts.length>0&&(<div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 mb-4"><div className="flex items-center gap-2 mb-2"><span className="text-lg pulse">⏰</span><span className="text-sm font-semibold text-amber-800">Prélèvements à venir</span></div>
      {alerts.map(e=>{let diff=e.jour_du_mois-todayDay;if(diff<0){const d=new Date(today.getFullYear(),today.getMonth()+1,0).getDate();diff=d-todayDay+e.jour_du_mois}return(<div key={e.id} className="flex justify-between items-center py-1.5"><span className="text-sm text-amber-900">{e.label}</span><div className="flex items-center gap-3"><span className="text-xs px-2 py-0.5 rounded-full bg-amber-200 text-amber-800">{diff===0?"Aujourd'hui":`J-${diff}`}</span><span className="text-sm font-semibold text-amber-900">{parseFloat(e.montant).toFixed(2)} €</span></div></div>)})}</div>) }
    <div className="flex gap-2 mb-4">{[{id:'depenses',label:'Dépenses communes'},{id:'echeances',label:'Echéances récurrentes'}].map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} className="flex-1 py-2.5 rounded-xl text-sm font-medium border transition-all" style={tab===t.id?{background:'#8B5E3C',color:'white',borderColor:'#8B5E3C'}:{background: 'white',color:'#6B7280',borderColor:'#E5E7EB'}}>{t.label}</button>))}</div>
    {tab==='depenses'&&(<>
      <div className="flex justify-between items-center bg-white rounded-xl border border-stone-100 px-4 py-3 mb-4"><span className="text-sm text-gray-500">Total commun</span><span className="text-xl font-semibold text-nid-warm">{total.toFixed(2)} €</span></div>
      <div className="bg-white rounded-2xl border border-stone-100 p-4 mb-4"><div className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">Ajouter</div><input value={labelInput} onChange={e=>setLabelInput(e.target.value)} placeholder="Libellé" className="w-full border border-stone-200 rounded-xl px-3 py-2.5 text-sm mb-2 focus:outline-none focus:border-nid-accent" /><div className="flex gap-2"><input value={montantInput} onChange={e=>setMontantInput(e.target.value)} type="number" placeholder="Montant €" step="0.01" className="flex-1 border border-stone-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-nid-accent" onKeyDown={e=>e.key==='Enter'&&addDepense()} /><button onClick={addDepense} className="px-5 py-2.5 rounded-xl text-sm font-medium text-white transition active:scale-95" style={{background:'#8B5E3C' }}>Ajouter</button></div></div>
      <div className="space-y-2">{sorted.map(dep=>{const prof=getProfile(dep.par);return(<div key={dep.id} className="bg-white rounded-2xl border p-4" style={{borderColor:dep.pinned?'#C4873B':'#F0EAE0',borderLeftWidth:dep.pinned?3:1}}><div className="flex justify-between items-start"><div className="flex-1"><div className="flex items-center gap-2">{dep.pinned&&<span>📌</span>}<span className="text-sm font-semibold text-gray-800">{eep.label}</span></div><div className="flex items-center gap-2 mt-1"><span className="text-xs px-2 py-0.5 rounded-full" style={{background:prof.bg,color:prof.color}}>{prof.petIcon} {prof.name}</span><span className="text-xs text-gray-400">{eep.date?format(parseISO(dep.date),'d MMM',{locale:fr}):''}</span></div></div><div className="text-lg font-semibold ml-4" style={{color:'#8B5E3C'}}>{parseFloat(dep.montant).toFixed(2)} €</div></div><div className="flex gap-2 mt-3"><button onClick={()=>togglePin(dep)} className="flex-1 py-1.5 text-xs rounded-lg border border-stone-200 text-gray-500 bg-stone-50 active:bg-stone-100">{dep.pinned?'Désépingler':'📌 Épingler'}</button><button onClick={()=>deleteDepense(dep.id)} className="flex-1 py-1.5 text-xs rounded-lg border border-red-100 text-red-400 bg-red-50 active:bg-red-100">Supprimer</button></div></div>)})}{sorted.length===0&&(<div className="text-center text-gray-400 text-sm py-8">Aucune dépense enregistrée</div>)}</div></>}
    {tab==='echeances'&&(<><div className="bg-white rounded-2xl border border-stone-100 p-4 mb-4"><div className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">Nouvelle échéance récurrente</div><input value={newEch.label} onChange={e=>setNewEch(n=>({...n,label:e.target.value}))} placeholder="Libellé" className="w-full border border-stone-200 rounded-xl px-3 py-2.5 text-sm mb-2 focus:outline-none focus:border-nid-accent" /><div className="flex gap-2"><input value={newEch.montant} onChange={e=>setNewEch(n=>({...n,montant:e.target.value}))} type="number" placeholder="Montant €" className="flex-1 border border-stone-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-nid-accent" /><input value={newEch.jour} onChange={e=>setNewEch(n=>({...n  ,jour:e.target.value}))} type="number" min="1" max="31" placeholder="Jour" className="w-20 border border-stone-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:border-nid-accent" /><button onClick={addEcheance} className="px-4 py-2.5 rounded-xl text-sm font-medium text-white transition active:scale-95" style={{background:'#8B5E3C' }}>+</button></div></div><div className="space-y-2">{echeances.map(e=>{let diff=e.jour_du_mois-todayDay;if(diff<0){const dim=new Date(today.getFullYear(),today.getMonth()+1,0).getDate();diff=dim-todayDay+b.jour_du_mois};const isAlert=diff<=5;return(<div key={e.id} className="bg-white rounded-2xl border p-4" style={{borderColor:isAlert&&e.actif?'#FCD34D':'#F0EAE0',opacity:e.actif?1:0.5}}><div className="flex justify-between items-center"><div><div className="flex items-center gap-2"><span className="text-sm font-semibold text-gray-800">{e.label}</span>{isAlert&&e.actif&&<span className="text-xs px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 pulse">J-{diff}</span>}</div><div className="text-xs text-gray-400 mt-0.5">Le {e.jour_du_mois} de chaque mois</div></div><div className="flex items-center gap-3"><span className="font-semibold text-nid-warm">{parseFloat(e.montant).toFixed(2)} €</span><button onClick={()=>toggleEcheance(e)} className={`toggle-switch ${e.actif?'on':''}`} /></div></div><button onClick={()=>deleteEcheance(e.id)} className="mt-2 text-xs text-red-400">Supprimer</button></div>)})}</div></>)}
  </div>)
}
